### ISSUE TITLE
A problem with memory usage by GDAL

### ISSUE THREAD

**Issue by sergeikharchenko** [GFZ/arosics#57] opened 2024-11-24 11:20 UTC
Dear colleagues! 

My stack:
* arosics version: 1.12.0
* Python version: 3.12.7
* Operating System: Win10 (with using WSL Ubuntu)

### Description
I have a problem with memory usage in GDAL using Arosics (but never before when using GDAL in other apps). But it seems it's a bug, because two images take only less than 200 mb, and I have free RAM ~ 25-30 gb.

### What I Did
```python
(arosics) sergey@DESKTOP-4UTK093:/mnt/c/arosics$ arosics global dem_hr_small.tif dem_lr_small.tif


Calculating footprint polygon and actual data corner coordinates for reference image...
Polygonize progress     |==================================================| 100.0% Complete  => 0:00:00
Bounding box of calculated footprint for reference image:
        (716810.3615290052, 4504286.795456652, 773228.0791082053, 4531719.8617350515)
Calculating footprint polygon and actual data corner coordinates for image to be shifted...
Bounding box of calculated footprint for image to be shifted:
        (716802.2038794053, 4504280.873456651, 773226.4115234053, 4531728.019384651)
Matching window position (X,Y): 745018.3865262053/4518003.328595852
Traceback (most recent call last):
  File "/home/sergey/miniconda3/envs/arosics/bin/arosics", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sergey/miniconda3/envs/arosics/lib/python3.12/site-packages/arosics/arosics_cli.py", line 363, in main
    parsed_args.func(parsed_args)
  File "/home/sergey/miniconda3/envs/arosics/lib/python3.12/site-packages/arosics/arosics_cli.py", line 69, in run_global_coreg
    COREG_obj.correct_shifts()
  File "/home/sergey/miniconda3/envs/arosics/lib/python3.12/site-packages/arosics/CoReg.py", line 1709, in correct_shifts
    DS = DESHIFTER(self.shift, self.coreg_info,
                               ^^^^^^^^^^^^^^^
  File "/home/sergey/miniconda3/envs/arosics/lib/python3.12/site-packages/arosics/CoReg.py", line 1649, in coreg_info
    self.calculate_spatial_shifts()
  File "/home/sergey/miniconda3/envs/arosics/lib/python3.12/site-packages/arosics/CoReg.py", line 1516, in calculate_spatial_shifts
    self._get_image_windows_to_match()  # 45-90ms
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergey/miniconda3/envs/arosics/lib/python3.12/site-packages/arosics/CoReg.py", line 1064, in _get_image_windows_to_match
    self.otherWin.arr, self.otherWin.gt = warp_ndarray(self.otherWin.arr,
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergey/miniconda3/envs/arosics/lib/python3.12/site-packages/py_tools_ds/geo/raster/reproject.py", line 476, in warp_ndarray
    res_ds = gdal.Warp(
             ^^^^^^^^^^
  File "/home/sergey/miniconda3/envs/arosics/lib/python3.12/site-packages/osgeo/gdal.py", line 1143, in Warp
    (opts, callback, callback_data) = WarpOptions(**kwargs)
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergey/miniconda3/envs/arosics/lib/python3.12/site-packages/osgeo/gdal.py", line 1118, in WarpOptions
    return (GDALWarpAppOptions(new_options), callback, callback_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergey/miniconda3/envs/arosics/lib/python3.12/site-packages/osgeo/gdal.py", line 9350, in __init__
    _gdal.GDALWarpAppOptions_swiginit(self, _gdal.new_GDALWarpAppOptions(*args))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to parse value of -wm
May be caused by: Memory size must be a positive number.
```

What should I do? Thanks!

Best regards,

**Comment by danschef** [comment] 2024-11-26 10:23
Not sure what happens there. Probably the WSL does not make enough memory available? You could use a tool like htop to monitor the system ressources within the WSL when running AROSICS.

I could try to reproduce it with your data if you want to make the data available somewhere.

**Comment by sergeikharchenko** [comment] 2024-11-26 15:19
I tried the same on very small rasters and got the same error. Also, I tried it on pure Ubuntu, not Windows. Same result.

I solved the problem (obviously not well and not in the right way) by commenting out the lines
```
if warpMemoryLimit is not None:
    new_options += ['-wm', str(warpMemoryLimit)]
```
in ./arosics/.../gdal.py

and giving a default value to the parameter
`warpMemoryLimit=None`
in the WarpOptions function.

I guess the problem is not in the files, but I still attach the source files.
https://drive.google.com/drive/folders/12aJ1fjy9pgKN6USUy6VWhJE9XWDArvQf?usp=sharing

Perhaps the topic can be closed. However, it is still interesting to know what is the cause of the problem.

**Comment by danschef** [comment] 2024-11-26 17:30
Ok, probably it is also somehow related to an updated version of gdal. Which gdal version is installed?

**Comment by sergeikharchenko** [comment] 2024-11-26 18:24
GDAL 3.10.0, released 2024/11/01

**Comment by danschef** [comment] 2024-11-27 10:56
This seems to be indeed due to changes introduced in GDAL 3.10. I can reproduce the error with GDAL 3.10.0 but if I downgrade GDAL to 3.9.3, all tests run through.

Thanks for reporting, I will fix this as soon as possible. Until then, you can just downgrade GDAL (`mamba install "gdal<3.10.0"` or so).

**Comment by danschef** [comment] 2024-11-27 11:32
The [fix](https://git.gfz-potsdam.de/danschef/py_tools_ds/-/merge_requests/52) will be included in py_tools_ds 0.23.1 which will soon be available on PyPI and conda-forge.

**Comment by danschef** [comment] 2024-11-27 18:28
Ok, you can now run mamba update py-tools-ds to get the fixed version.

**Closed by danschef** 2024-11-27 18:28 UTC

**Comment by sergeikharchenko** [comment] 2024-11-27 18:45
Thanks a lot for your tool and your help!
